name: CraftingAdditions
version: ${project.version}
main: xyz.fluxinc.craftingadditions.CraftingAdditions
api-version: 1.13
authors: [CelesteMagisteel]
description: Adds some additions to the crafting system, to make life easier
website: http://fluxinc.xyz
